name: invoiceapp
description: A InvoiceApp.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  shared_preferences: ^2.0.20
  http: ^0.13.5
  image_picker: ^0.8.7
  google_fonts: ^4.0.3
  multi_image_picker2: any
  flutter_absolute_path: ^1.0.6
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.14
  dropdown_button2: ^1.8.1
#  modal_bottom_sheet: ^2.1.2
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  uuid: ^3.0.7
  collection:
  provider: ^6.0.5
  file: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
